export const MINIMUM_IP_RETRIEVE_TIMEOUT_MS = 1_000;
export const MINIMUM_IP_RETRIEVE_UPDATE_DIFF_MS = 3_000;

export const CHANGE_INSYNC_INTERVAL_MS = 15_000;
export const CHANGE_INSYNC_LIMIT_MS = 5 * 60 * 1000;
