---
services:
  node-route53-dynamic-dns:
    image: linkedmink/node-route53-dynamic-dns:latest
    command: [ "npm", "run", "start:built", "--", "--env-file", "/run/secrets/.env.secrets" ]
    ports:
      - 61080:61080
    restart: always
    environment:
      - LOG_LEVEL=verbose
      - BIND_PORT=61080
      - IP_V6_ENABLED=false
      - HOSTNAMES_TO_UPDATE=["myhost.public.tld"]
    secrets:
      - source: secrets-env
        target: .env.secrets
        uid: '1000'
        gid: '1000'
        mode: 0400

secrets:
  secrets-env:
    file: ./secrets.env

networks:
  default:
    name: node-route53-dynamic-dns-bridge
    # sudo docker network create node-route53-dynamic-dns-bridge
    # external: true
