FROM oven/bun:1-alpine

ARG ENVIRONMENT=production

ENV NODE_ENV ENVIRONMENT
ENV IS_CONTAINER_ENV true

RUN cat /etc/passwd

WORKDIR /home/bun

COPY --chown=1000:1000 . .

USER bun

RUN bun install --frozen-lockfile --production

RUN ls -la ./

CMD [ "node", "--enable-source-maps", "dist/index.mjs" ]
