name: Build ref

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    uses: LinkedMink/shared-scripts/.github/workflows/build-npm-package.yml@main
    with:
      uploadBuild: false
