name: Build ref
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches-ignore:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    uses: LinkedMink/node-route53-dynamic-dns/.github/workflows/build.yml@main
    with:
      uploadBuild: false
